name: Testing

on:
  push:
    branches: 
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello, Sulabh!"

      - name: how are you?
        run: echo "I'm fine"
